/*
 * acs_apgcc_error.h
 *
 *  Created on: Dec 30, 2010
 *      Author: xfabron
 */

#ifndef ACS_APGCC_ERROR_H_
#define ACS_APGCC_ERROR_H_



/* the following defines are intended to wrap the IMM error
 * */
#define ACS_APGCC_NO_ERR "NO_ERROR"
#define ACS_APGCC_ERR_UNKNOW "ERR_UNKNOW"
#define ACS_APGCC_ERR_IMM_LIBRARY "ERR_IMM_LIBRARY"
#define ACS_APGCC_ERR_IMM_VERSION "ERR_IMM_VERSION"
#define ACS_APGCC_ERR_IMM_INIT "ERR_IMM_INIT"
#define ACS_APGCC_ERR_IMM_TIMEOUT "ERR_IMM_TIMEOUT"
#define ACS_APGCC_ERR_IMM_TRY_AGAIN "ERR_IMM_TRY_AGAIN"
#define ACS_APGCC_ERR_IMM_INVALID_PARAM "ERR_INVALID_PARAMETER"
#define ACS_APGCC_ERR_IMM_NO_MEMORY "ERR_IMM_NO_MEMORY"
#define ACS_APFCC_ERR_IMM_BAD_HANDLE "ERR_IMM_BAD_HANDLE"
#define ACS_APGCC_ERR_IMM_BUSY "ERR_IMM_BUSY"
#define ACS_APGCC_ERR_IMM_ACCESS "ERR_IMM_ACCESS"
#define ACS_APGCC_ERR_IMM_NOT_EXIST "ERR_ELEMENT_NOT_EXIST"
#define ACS_APGCC_ERR_IMM_NAME_TOO_LONG "ERR_NAME_TOO_LONG"
#define ACS_APGCC_ERR_IMM_EXIST "ERR_ELEMENT_ALREADY_EXIST"
#define ACS_APGCC_ERR_IMM_NO_SPACE "ERR_IMM_NO_SPACE"
#define ACS_APGCC_ERR_IMM_INTERRUPT "ERR_IMM_INTERRUPT"
#define ACS_APGCC_ERR_NAME_NOT_FOUND "ERR_NAME_NOT_FOUND"
#define ACS_APGCC_ERR_IMM_NO_RESOURCES "ERR_IMM_NO_RESOURCES"
#define ACS_APGCC_ERR_IMM_NOT_SUPPORTED "ERR_IMM_NOT_SUPPORTED"
#define ACS_APGCC_ERR_IMM_BAD_OPERATION "ERR_IMM_BAD_OPERATION"
#define ACS_APGCC_ERR_IMM_FAILED_OPERATION "ERR_IMM_FAILED_OPERATION"
#define ACS_APGCC_ERR_IMM_MESSAGE_ERROR "ERR_IMM_MESSAGE_ERROR"
#define ACS_APGCC_ERR_IMM_QUEUE_FULL "ERR_IMM_QUEUE_FULL"
#define ACS_APGCC_ERR_IMM_QUEUE_NOT_AVAILABLE "ERR_IMM_QUEUE_NOT_AVAILABLE"
#define ACS_APGCC_ERR_IMM_BAD_FLAGS "ERR_IMM_BAD_FLAGS"
#define ACS_APGCC_ERR_IMM_TOO_BIG "ERR_IMM_TOO_BIG"
#define ACS_APGCC_ERR_IMM_NO_SECTIONS "ERR_IMM_NO_SECTION"
#define ACS_APGCC_ERR_IMM_NO_OP "ERR_IMM_NO_OP"
#define ACS_APGCC_ERR_IMM_REPAIR_PENDING "ERR_IMM_REPAIR_PENDING"
#define ACS_APGCC_ERR_IMM_NO_BINDINGS "ERR_IMM_NO_BINDINGS"
#define ACS_APGCC_ERR_IMM_UNAVAILABLE "ERR_IMM_UNAVAILABLE"
#define ACS_APGCC_ERR_IMM_CAMPAIGN_ERR_DETECTED "ERR_IMM_CAMPAIGN_ERR_DETECTED"
#define ACS_APGCC_ERR_IMM_CAMPAIGN_PROC_FAILED "ERR_IMM_CAMPAIGN_PROC_FAILED"
#define ACS_APGCC_ERR_IMM_CAMPAIGN_CANCELED "ERR_IMM_CAMPAIGN_CANCELED"
#define ACS_APGCC_ERR_IMM_CAMPAIGN_FAILED "ERR_IMM_CAMPAIGN_FAILED"
#define ACS_APGCC_ERR_IMM_CAMPAIGN_SUSPENDED "ERR_IMM_CAMPAIGN_SUSPENDED"
#define ACS_APGCC_ERR_IMM_CAMPAIGN_SUSPENDING "ERR_IMM_CAMPAIGN_SUSPENDING"
#define ACS_APGCC_ERR_IMM_ACCESS_DENIED "ERR_IMM_ACCESS_DENIED"
#define ACS_APGCC_ERR_IMM_NOT_READY "ERR_IMM_NOT_READY"
#define ACS_APGCC_ERR_IMM_DEPLOYMENT "ERR_IMM_DEPLOYMENT"
#define ACS_APGCC_ERR_NOT_FOUND "ELEMENT_NOT_FOUND"
#define ACS_APGCC_ERR_TRANSACTION_NOT_FOUND "TRANSACTION_NOT_FOUND"
#define ACS_APGCC_ERR_IMM_SAVE "IMM-SAVE_FAILED"
#define ACS_APGCC_ERR_GENERIC "GENERIC_ERROR"

#define ACS_APGCC_MAX_ERROR_NUMBER 45


static char * errorArray[ACS_APGCC_MAX_ERROR_NUMBER] = {
		const_cast<char *>(ACS_APGCC_NO_ERR), 									//0
		const_cast<char *>(ACS_APGCC_ERR_UNKNOW),								//1
		const_cast<char *>(ACS_APGCC_ERR_IMM_LIBRARY),							//2
		const_cast<char *>(ACS_APGCC_ERR_IMM_VERSION),							//3
		const_cast<char *>(ACS_APGCC_ERR_IMM_INIT),								//4
		const_cast<char *>(ACS_APGCC_ERR_IMM_TIMEOUT),							//5
		const_cast<char *>(ACS_APGCC_ERR_IMM_TRY_AGAIN),						//6
		const_cast<char *>(ACS_APGCC_ERR_IMM_INVALID_PARAM),					//7
		const_cast<char *>(ACS_APGCC_ERR_IMM_NO_MEMORY),						//8
		const_cast<char *>(ACS_APFCC_ERR_IMM_BAD_HANDLE),						//9
		const_cast<char *>(ACS_APGCC_ERR_IMM_BUSY),								//10
		const_cast<char *>(ACS_APGCC_ERR_IMM_ACCESS),							//11
		const_cast<char *>(ACS_APGCC_ERR_IMM_NOT_EXIST),						//12
		const_cast<char *>(ACS_APGCC_ERR_IMM_NAME_TOO_LONG),					//13
		const_cast<char *>(ACS_APGCC_ERR_IMM_EXIST),							//14
		const_cast<char *>(ACS_APGCC_ERR_IMM_NO_SPACE),							//15
		const_cast<char *>(ACS_APGCC_ERR_IMM_INTERRUPT),						//16
		const_cast<char *>(ACS_APGCC_ERR_NAME_NOT_FOUND),						//17
		const_cast<char *>(ACS_APGCC_ERR_IMM_NO_RESOURCES),						//18
		const_cast<char *>(ACS_APGCC_ERR_IMM_NOT_SUPPORTED),					//19
		const_cast<char *>(ACS_APGCC_ERR_IMM_BAD_OPERATION),					//20
		const_cast<char *>(ACS_APGCC_ERR_IMM_FAILED_OPERATION),					//21
		const_cast<char *>(ACS_APGCC_ERR_IMM_MESSAGE_ERROR),					//22
		const_cast<char *>(ACS_APGCC_ERR_IMM_QUEUE_FULL),						//23
		const_cast<char *>(ACS_APGCC_ERR_IMM_QUEUE_NOT_AVAILABLE),				//24
		const_cast<char *>(ACS_APGCC_ERR_IMM_BAD_FLAGS),						//25
		const_cast<char *>(ACS_APGCC_ERR_IMM_TOO_BIG),							//26
		const_cast<char *>(ACS_APGCC_ERR_IMM_NO_SECTIONS),						//27
		const_cast<char *>(ACS_APGCC_ERR_IMM_NO_OP),							//28
		const_cast<char *>(ACS_APGCC_ERR_IMM_REPAIR_PENDING),					//29
		const_cast<char *>(ACS_APGCC_ERR_IMM_NO_BINDINGS),						//30
		const_cast<char *>(ACS_APGCC_ERR_IMM_UNAVAILABLE),						//31
		const_cast<char *>(ACS_APGCC_ERR_IMM_CAMPAIGN_ERR_DETECTED),			//32
		const_cast<char *>(ACS_APGCC_ERR_IMM_CAMPAIGN_PROC_FAILED),				//33
		const_cast<char *>(ACS_APGCC_ERR_IMM_CAMPAIGN_CANCELED),				//34
		const_cast<char *>(ACS_APGCC_ERR_IMM_CAMPAIGN_FAILED),					//35
		const_cast<char *>(ACS_APGCC_ERR_IMM_CAMPAIGN_SUSPENDED),				//36
		const_cast<char *>(ACS_APGCC_ERR_IMM_CAMPAIGN_SUSPENDING),				//37
		const_cast<char *>(ACS_APGCC_ERR_IMM_ACCESS_DENIED),					//38
		const_cast<char *>(ACS_APGCC_ERR_IMM_NOT_READY),						//39
		const_cast<char *>(ACS_APGCC_ERR_IMM_DEPLOYMENT),						//40
		const_cast<char *>(ACS_APGCC_ERR_NOT_FOUND),							//41
		const_cast<char *>(ACS_APGCC_ERR_TRANSACTION_NOT_FOUND),				//42
		const_cast<char *>(ACS_APGCC_ERR_IMM_SAVE),								//43
		const_cast<char *>(ACS_APGCC_ERR_GENERIC)								//44
};



#endif /* ACS_APGCC_ERROR_H_ */
