#include "ACS_DSD_TraTracer.h"

#include "ACS_DSD_PrimitiveDataHandler.h"

#ifdef ACS_DSD_API_TRACING_ACTIVE
ACS_DSD_API_CLASS_TRACER_DECL(__CLASS_NAME__)(ACS_DSD_STRINGIZE(__CLASS_NAME__));
#endif

const uint8_t ACS_DSD_PCP_PRIMITIVE_FIELDS_COUNTS[acs_dsd::PCP_SUPPORTED_VERSION_COUNT][acs_dsd::PCP_PRIMITIVES_RANGE_COUNT] = {
	{ // Version 1
		//CP-AP PRIM ID: 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  19 20 21 22 23 24 25 26 27 28 29 30
										 2, 4, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

		//DSDAPI PRIM ID: 31 32 33 34 35 36 37 38 39 40 41  42  43 44 45 46 47 48 49 50
										  12, 8, 3, 4, 3, 6, 7, 4, 6, 5, 6, 13, 10, 3, 3, 2, 6, 0, 0, 0,

		//DSD PRIM ID: 51 52 53 54 55 56 57  58 59 60 61 62  63  64 65 66 67 68
										6, 8, 5, 2, 5, 4, 6, 14, 3, 5, 3, 4, 14, 10, 5, 6, 7, 3
	},
	{ // Version 2
		//CP-AP PRIM ID: 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
										 2, 4, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0,

		//DSDAPI PRIM ID: 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
											 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

		//DSD PRIM ID: 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
										0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
	}
};

const uint16_t ACS_DSD_PCP_PRIMITIVE_FIELDS_SIZES[acs_dsd::PCP_SUPPORTED_VERSION_COUNT][acs_dsd::PCP_PRIMITIVES_RANGE_COUNT][acs_dsd::PCP_FIELD_COUNT_MAX] = {
	{ //Version 1
		/*PRIM  0*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_UNKNOWN},
		/*PRIM  1*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_NODE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME},
		/*PRIM  2*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_CONNECTION_TYPE,acs_dsd::PCP_FIELD_SIZE_CONNECTION_COUNT,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER},
		/*PRIM  3*/ {0},
		/*PRIM  4*/ {0},
		/*PRIM  5*/ {0},
		/*PRIM  6*/ {0},
		/*PRIM  7*/ {0},
		/*PRIM  8*/ {0},
		/*PRIM  9*/ {0},
		/*PRIM 10*/ {0},
		/*PRIM 11*/ {0},
		/*PRIM 12*/ {0},
		/*PRIM 13*/ {0},
		/*PRIM 14*/ {0},
		/*PRIM 15*/ {0},
		/*PRIM 16*/ {0},
		/*PRIM 17*/ {0},
		/*PRIM 18*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 19*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_CONNECTION_TYPE,acs_dsd::PCP_FIELD_SIZE_CONNECTION_COUNT,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER},
		/*PRIM 20*/ {0},
		/*PRIM 21*/ {0},
		/*PRIM 22*/ {0},
		/*PRIM 23*/ {0},
		/*PRIM 24*/ {0},
		/*PRIM 25*/ {0},
		/*PRIM 26*/ {0},
		/*PRIM 27*/ {0},
		/*PRIM 28*/ {0},
		/*PRIM 29*/ {0},
		/*PRIM 30*/ {0},
		/*PRIM 31*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_ID,acs_dsd::PCP_FIELD_SIZE_VISIBILITY,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH},
		/*PRIM 32*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_ID,acs_dsd::PCP_FIELD_SIZE_VISIBILITY,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH},
		/*PRIM 33*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE},
		/*PRIM 34*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME},
		/*PRIM 35*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE},
		/*PRIM 36*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE},
		/*PRIM 37*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER},
		/*PRIM 38*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH},
		/*PRIM 39*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_QUERY_ORDER,acs_dsd::PCP_FIELD_SIZE_TIMEOUT_4_BYTES},
		/*PRIM 40*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE},
		/*PRIM 41*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_LIST_ORDER,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME},
		/*PRIM 42*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_ID,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER},
		/*PRIM 43*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_ID,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH},
		/*PRIM 44*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID},
		/*PRIM 45*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_SPX_STATE},
		/*PRIM 46*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION},
		/*PRIM 47*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 48*/ {0},
		/*PRIM 49*/ {0},
		/*PRIM 50*/ {0},
		/*PRIM 51*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE},
		/*PRIM 52*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_NODE_STATE},
		/*PRIM 53*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH,acs_dsd::PCP_FIELD_SIZE_NODE_STATE},
		/*PRIM 54*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION},
		/*PRIM 55*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 56*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME},
		/*PRIM 57*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 58*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_NAME,acs_dsd::PCP_FIELD_SIZE_NODE_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_ID,acs_dsd::PCP_FIELD_SIZE_VISIBILITY,acs_dsd::PCP_FIELD_SIZE_CONNECTION_TYPE,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH},
		/*PRIM 59*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE},
		/*PRIM 60*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 61*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE},
		/*PRIM 62*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 63*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_ID,acs_dsd::PCP_FIELD_SIZE_VISIBILITY,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH},
		/*PRIM 64*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_NAME,acs_dsd::PCP_FIELD_SIZE_PROCESS_ID,acs_dsd::PCP_FIELD_SIZE_VISIBILITY,acs_dsd::PCP_FIELD_SIZE_UNIX_SOCK_PATH},
		/*PRIM 65*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 66*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_STATE,acs_dsd::PCP_FIELD_SIZE_NODE_NAME},
		/*PRIM 67*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_FBN,acs_dsd::PCP_FIELD_SIZE_OP_TYPE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_TYPE,acs_dsd::PCP_FIELD_SIZE_SYSTEM_ID,acs_dsd::PCP_FIELD_SIZE_NODE_SIDE},
		/*PRIM 68*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE}
	},
	{ //Version 2
		/*PRIM  0*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_UNKNOWN},
		/*PRIM  1*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_NODE_NAME,acs_dsd::PCP_FIELD_SIZE_APP_DOMAIN_NAME,acs_dsd::PCP_FIELD_SIZE_APP_SERVICE_NAME},
		/*PRIM  2*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_CONNECTION_TYPE,acs_dsd::PCP_FIELD_SIZE_CONNECTION_COUNT,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_PORT_NUMBER},
		/*PRIM  3*/ {0},
		/*PRIM  4*/ {0},
		/*PRIM  5*/ {0},
		/*PRIM  6*/ {0},
		/*PRIM  7*/ {0},
		/*PRIM  8*/ {0},
		/*PRIM  9*/ {0},
		/*PRIM 10*/ {0},
		/*PRIM 11*/ {0},
		/*PRIM 12*/ {0},
		/*PRIM 13*/ {0},
		/*PRIM 14*/ {0},
		/*PRIM 15*/ {0},
		/*PRIM 16*/ {0},
		/*PRIM 17*/ {0},
		/*PRIM 18*/ {0},
		/*PRIM 19*/ {0},
		/*PRIM 20*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_AP_MASK,acs_dsd::PCP_FIELD_SIZE_CP_MASK,acs_dsd::PCP_FIELD_SIZE_CP_MASK,acs_dsd::PCP_FIELD_SIZE_AP_IDENTITY},
		/*PRIM 21*/ {acs_dsd::PCP_FIELD_SIZE_PRIMITIVE_ID,acs_dsd::PCP_FIELD_SIZE_VERSION,acs_dsd::PCP_FIELD_SIZE_PROT_ERROR_CODE,acs_dsd::PCP_FIELD_SIZE_AP_IDENTITY,acs_dsd::PCP_FIELD_SIZE_RESERVED_1_BYTE,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS,acs_dsd::PCP_FIELD_SIZE_IPV4_ADDRESS},
		/*PRIM 22*/ {0},
		/*PRIM 23*/ {0},
		/*PRIM 24*/ {0},
		/*PRIM 25*/ {0},
		/*PRIM 26*/ {0},
		/*PRIM 27*/ {0},
		/*PRIM 28*/ {0},
		/*PRIM 29*/ {0},
		/*PRIM 30*/ {0},
		/*PRIM 31*/ {0},
		/*PRIM 32*/ {0},
		/*PRIM 33*/ {0},
		/*PRIM 34*/ {0},
		/*PRIM 35*/ {0},
		/*PRIM 36*/ {0},
		/*PRIM 37*/ {0},
		/*PRIM 38*/ {0},
		/*PRIM 39*/ {0},
		/*PRIM 40*/ {0},
		/*PRIM 41*/ {0},
		/*PRIM 42*/ {0},
		/*PRIM 43*/ {0},
		/*PRIM 44*/ {0},
		/*PRIM 45*/ {0},
		/*PRIM 46*/ {0},
		/*PRIM 47*/ {0},
		/*PRIM 48*/ {0},
		/*PRIM 49*/ {0},
		/*PRIM 50*/ {0},
		/*PRIM 51*/ {0},
		/*PRIM 52*/ {0},
		/*PRIM 53*/ {0},
		/*PRIM 54*/ {0},
		/*PRIM 55*/ {0},
		/*PRIM 56*/ {0},
		/*PRIM 57*/ {0},
		/*PRIM 58*/ {0},
		/*PRIM 59*/ {0},
		/*PRIM 60*/ {0},
		/*PRIM 61*/ {0},
		/*PRIM 62*/ {0},
		/*PRIM 63*/ {0},
		/*PRIM 64*/ {0},
		/*PRIM 65*/ {0},
		/*PRIM 66*/ {0},
		/*PRIM 67*/ {0},
		/*PRIM 68*/ {0}
	}
};

const copier<void> _null_copier_object;

namespace {
	const copier<byte_type> _byte_copier;
	const copier<string_type> _string_copier;
	const copier<two_bytes_host_order_type> _two_bytes_host_order_copier;
	const copier<two_bytes_net_order_type> _two_bytes_net_order_copier;
	const copier<four_bytes_host_order_type> _four_bytes_host_order_copier;
	const copier<four_bytes_net_order_type> _four_bytes_net_order_copier;
	const copier<eight_bytes_little_endian_order_type> _eight_bytes_little_endian_order_copier;
}

const copy_caller ACS_DSD_PCP_PRIMITIVE_FIELDS_COPIER_CALLERS[acs_dsd::PCP_SUPPORTED_VERSION_COUNT][acs_dsd::PCP_PRIMITIVES_RANGE_COUNT][acs_dsd::PCP_FIELD_COUNT_MAX] = {
	{ //Version 1
		/*PRIM  0*/ {copy_caller(),copy_caller(_byte_copier)},
		/*PRIM  1*/ {copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier)},
		/*PRIM  2*/ {copy_caller(),copy_caller(_byte_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier)},
		/*PRIM  3*/ {copy_caller()},
		/*PRIM  4*/ {copy_caller()},
		/*PRIM  5*/ {copy_caller()},
		/*PRIM  6*/ {copy_caller()},
		/*PRIM  7*/ {copy_caller()},
		/*PRIM  8*/ {copy_caller()},
		/*PRIM  9*/ {copy_caller()},
		/*PRIM 10*/ {copy_caller()},
		/*PRIM 11*/ {copy_caller()},
		/*PRIM 12*/ {copy_caller()},
		/*PRIM 13*/ {copy_caller()},
		/*PRIM 14*/ {copy_caller()},
		/*PRIM 15*/ {copy_caller()},
		/*PRIM 16*/ {copy_caller()},
		/*PRIM 17*/ {copy_caller()},
		/*PRIM 18*/ {copy_caller(),copy_caller(),copy_caller(_string_copier)},
		/*PRIM 19*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier)},
		/*PRIM 20*/ {copy_caller()},
		/*PRIM 21*/ {copy_caller()},
		/*PRIM 22*/ {copy_caller()},
		/*PRIM 23*/ {copy_caller()},
		/*PRIM 24*/ {copy_caller()},
		/*PRIM 25*/ {copy_caller()},
		/*PRIM 26*/ {copy_caller()},
		/*PRIM 27*/ {copy_caller()},
		/*PRIM 28*/ {copy_caller()},
		/*PRIM 29*/ {copy_caller()},
		/*PRIM 30*/ {copy_caller()},
		/*PRIM 31*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_string_copier)},
		/*PRIM 32*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 33*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier)},
		/*PRIM 34*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier)},
		/*PRIM 35*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier)},
		/*PRIM 36*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier)},
		/*PRIM 37*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier)},
		/*PRIM 38*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 39*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier)},
		/*PRIM 40*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier)},
		/*PRIM 41*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_string_copier),copy_caller(_string_copier)},
		/*PRIM 42*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier)},
		/*PRIM 43*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_string_copier)},
		/*PRIM 44*/ {copy_caller(),copy_caller(),copy_caller(_four_bytes_host_order_copier)},
		/*PRIM 45*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier)},
		/*PRIM 46*/ {copy_caller(),copy_caller()},
		/*PRIM 47*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 48*/ {copy_caller()},
		/*PRIM 49*/ {copy_caller()},
		/*PRIM 50*/ {copy_caller()},
		/*PRIM 51*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier)},
		/*PRIM 52*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_byte_copier)},
		/*PRIM 53*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_string_copier),copy_caller(_byte_copier)},
		/*PRIM 54*/ {copy_caller(),copy_caller()},
		/*PRIM 55*/ {copy_caller(),copy_caller(),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 56*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier)},
		/*PRIM 57*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 58*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_string_copier)},
		/*PRIM 59*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier)},
		/*PRIM 60*/ {copy_caller(),copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier)},
		/*PRIM 61*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier)},
		/*PRIM 62*/ {copy_caller(),copy_caller(),copy_caller(_four_bytes_host_order_copier),copy_caller(_string_copier)},
		/*PRIM 63*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_string_copier)},
		/*PRIM 64*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 65*/ {copy_caller(),copy_caller(),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 66*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier),copy_caller(_string_copier)},
		/*PRIM 67*/ {copy_caller(),copy_caller(),copy_caller(_two_bytes_net_order_copier),copy_caller(_byte_copier),copy_caller(_two_bytes_net_order_copier),copy_caller(_four_bytes_net_order_copier),copy_caller(_byte_copier)},
		/*PRIM 68*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier)}
	},
	{ //Version 2
		/*PRIM  0*/ {copy_caller(),copy_caller(_byte_copier)},
		/*PRIM  1*/ {copy_caller(),copy_caller(_string_copier),copy_caller(_string_copier),copy_caller(_string_copier)},
		/*PRIM  2*/ {copy_caller(),copy_caller(_byte_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_two_bytes_host_order_copier)},
		/*PRIM  3*/ {copy_caller()},
		/*PRIM  4*/ {copy_caller()},
		/*PRIM  5*/ {copy_caller()},
		/*PRIM  6*/ {copy_caller()},
		/*PRIM  7*/ {copy_caller()},
		/*PRIM  8*/ {copy_caller()},
		/*PRIM  9*/ {copy_caller()},
		/*PRIM 10*/ {copy_caller()},
		/*PRIM 11*/ {copy_caller()},
		/*PRIM 12*/ {copy_caller()},
		/*PRIM 13*/ {copy_caller()},
		/*PRIM 14*/ {copy_caller()},
		/*PRIM 15*/ {copy_caller()},
		/*PRIM 16*/ {copy_caller()},
		/*PRIM 17*/ {copy_caller()},
		/*PRIM 18*/ {copy_caller()},
		/*PRIM 19*/ {copy_caller()},
		/*PRIM 20*/ {copy_caller(),copy_caller(),copy_caller(_eight_bytes_little_endian_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_byte_copier)},
		/*PRIM 21*/ {copy_caller(),copy_caller(),copy_caller(_byte_copier),copy_caller(_byte_copier),copy_caller(_byte_copier),copy_caller(_four_bytes_host_order_copier),copy_caller(_four_bytes_host_order_copier)},
		/*PRIM 22*/ {copy_caller()},
		/*PRIM 23*/ {copy_caller()},
		/*PRIM 24*/ {copy_caller()},
		/*PRIM 25*/ {copy_caller()},
		/*PRIM 26*/ {copy_caller()},
		/*PRIM 27*/ {copy_caller()},
		/*PRIM 28*/ {copy_caller()},
		/*PRIM 29*/ {copy_caller()},
		/*PRIM 30*/ {copy_caller()},
		/*PRIM 31*/ {copy_caller()},
		/*PRIM 32*/ {copy_caller()},
		/*PRIM 33*/ {copy_caller()},
		/*PRIM 34*/ {copy_caller()},
		/*PRIM 35*/ {copy_caller()},
		/*PRIM 36*/ {copy_caller()},
		/*PRIM 37*/ {copy_caller()},
		/*PRIM 38*/ {copy_caller()},
		/*PRIM 39*/ {copy_caller()},
		/*PRIM 40*/ {copy_caller()},
		/*PRIM 41*/ {copy_caller()},
		/*PRIM 42*/ {copy_caller()},
		/*PRIM 43*/ {copy_caller()},
		/*PRIM 44*/ {copy_caller()},
		/*PRIM 45*/ {copy_caller()},
		/*PRIM 46*/ {copy_caller()},
		/*PRIM 47*/ {copy_caller()},
		/*PRIM 48*/ {copy_caller()},
		/*PRIM 49*/ {copy_caller()},
		/*PRIM 50*/ {copy_caller()},
		/*PRIM 51*/ {copy_caller()},
		/*PRIM 52*/ {copy_caller()},
		/*PRIM 53*/ {copy_caller()},
		/*PRIM 54*/ {copy_caller()},
		/*PRIM 55*/ {copy_caller()},
		/*PRIM 56*/ {copy_caller()},
		/*PRIM 57*/ {copy_caller()},
		/*PRIM 58*/ {copy_caller()},
		/*PRIM 59*/ {copy_caller()},
		/*PRIM 60*/ {copy_caller()},
		/*PRIM 61*/ {copy_caller()},
		/*PRIM 62*/ {copy_caller()},
		/*PRIM 63*/ {copy_caller()},
		/*PRIM 64*/ {copy_caller()},
		/*PRIM 65*/ {copy_caller()},
		/*PRIM 66*/ {copy_caller()},
		/*PRIM 67*/ {copy_caller()},
		/*PRIM 68*/ {copy_caller()}
	}
};
