//*****************************************************************************
//
// .NAME
//     ACS_APGCC_EventCodes - ACS_APGCC Event Codes.
// .LIBRARY 3C++
// .PAGENAME MCS_MCC
// .HEADER  MCS
// .LEFT_FOOTER Ericsson Utvecklings AB
// .INCLUDE MCS_EventCodes.H

// .COPYRIGHT
//  COPYRIGHT Ericsson Utvecklings AB, Sweden 1997.
//  All rights reserved.
//
//  The Copyright to the computer program(s) herein
//  is the property of Ericsson Utvecklings AB, Sweden.
//  The program(s) may be used and/or copied only with
//  the written permission from Ericsson Utvecklings AB or in
//  accordance with the terms and conditions stipulated in the
//  agreement/contract under which the program(s) have been
//  supplied.

// .DESCRIPTION
//
//  Defines all available event codes for MCS.
//  To be used internally only.

// .ERROR HANDLING
//
//  .fill_off
//  General rule:
//  -
//
//  .fill_on

// DOCUMENT NO
//      190 89-CAA 109 0171

// AUTHOR
//      1998-03-18 by UAB/I/LN  UABSJEN

// .REVISION
//      A       98-03-18

// CHANGES
//
//      RELEASE REVISION HISTORY
//
//      REV NO          DATE            NAME            DESCRIPTION
//      A               98-03-18        SJEN            First release

// .LINKAGE
//      -

//*****************************************************************************

#ifndef ACS_APGCC_EVENTCODES_H_
#define ACS_APGCC_EVENTCODES_H_

typedef int ACS_APGCC_EventCode;
#  include "ACS_APGCC_ErrorCodes.H"
#endif /* ACS_APGCC_EVENTCODES_H_ */
