/*
 * acs_prc_brfDefine.h
 *
 *  Created on: Jul 9, 2012
 *      Author: xlucpet
 */

#ifndef ACS_PRC_BRFDEFINE_H_
#define ACS_PRC_BRFDEFINE_H_

#define BRM_SYSTEM_BACKUP_MANAGER__CREATE_BACKUP	0
#define BRM_SYSTEM_BACKUP_MANAGER__DELETE  	1
#define BRM_SYSTEM_BACKUP__RESTORE 3
#define BRM_SYSTEM_BACKUP__CONFIRM_RESTORE 4
#define BRM_SYSTEM_BACKUP__CANCEL_CURRENT_ACTION 5

#define BRF_VERSION_PRA_

#ifndef BRF_VERSION_PRA_

#define BRM_PARTICIPANT__PERMIT_BACKUP 6
#define BRM_PARTICIPANT__COMMIT_BACKUP 7
#define BRM_PARTICIPANT__CANCEL_BACKUP 8

#define BRM_PERSISTENT_DATA_OWNER__PREPARE_BACKUP 9

#define BRM_PERSISTENT_STORAGE_OWNER__CREATE_BACKUP 10
#define BRM_PERSISTENT_STORAGE_OWNER__PERMIT_DELETE 11
#define BRM_PERSISTENT_STORAGE_OWNER__PREPARE_DELETE 12
#define BRM_PERSISTENT_STORAGE_OWNER__COMMIT_DELETE 13
#define BRM_PERSISTENT_STORAGE_OWNER__CANCEL_DELETE 14
#define BRM_PERSISTENT_STORAGE_OWNER__PERMIT_RESTORE 15
#define BRM_PERSISTENT_STORAGE_OWNER__PREPARE_RESTORE 16
#define BRM_PERSISTENT_STORAGE_OWNER__COMMIT_RESTORE 17
#define BRM_PERSISTENT_STORAGE_OWNER__CANCEL_RESTORE 18

#define BRM_PARTICIPANT_CONTAINER__REPORT_ACTION_PROGRESS 19
#define BRM_PARTICIPANT_CONTAINER__REPORT_ACTION_RESULT 20

#else

#define BRM_PARTICIPANT__PERMIT_BACKUP 0
#define BRM_PARTICIPANT__COMMIT_BACKUP 3
#define BRM_PARTICIPANT__CANCEL_BACKUP 4

#define BRM_PERSISTENT_DATA_OWNER__PREPARE_BACKUP 1

#define BRM_PERSISTENT_STORAGE_OWNER__CREATE_BACKUP 2
#define BRM_PERSISTENT_STORAGE_OWNER__PERMIT_DELETE 5
#define BRM_PERSISTENT_STORAGE_OWNER__PREPARE_DELETE 6
#define BRM_PERSISTENT_STORAGE_OWNER__COMMIT_DELETE 7
#define BRM_PERSISTENT_STORAGE_OWNER__CANCEL_DELETE 8
#define BRM_PERSISTENT_STORAGE_OWNER__PERMIT_RESTORE 9
#define BRM_PERSISTENT_STORAGE_OWNER__PREPARE_RESTORE 10
#define BRM_PERSISTENT_STORAGE_OWNER__COMMIT_RESTORE 11
#define BRM_PERSISTENT_STORAGE_OWNER__CANCEL_RESTORE 12

#define BRM_PARTICIPANT_CONTAINER__REPORT_ACTION_PROGRESS 21
#define BRM_PARTICIPANT_CONTAINER__REPORT_ACTION_RESULT 22

#endif

// Define status for backupType parameter

#define BRF_SUCCESS 	0
#define BRF_ERROR_DISKSPACE 1
#define BRF_ERROR_CONFLICT 	2
#define BRF_ERROR_OTHERS	99

#endif /* ACS_PRC_BRFDEFINE_H_ */
