/*
 * acs_bur_BrfcAdminOperationId.h
 *
 *  Created on: Jul 13, 2012
 *      Author: egiacri
 */

#ifndef ACS_BUR_BRFCADMINOPERATIONID_H_
#define ACS_BUR_BRFCADMINOPERATIONID_H_

typedef enum
{
	BRM_SYSTEM_BACKUP_MANAGER__CREATE_BACKUP = 0,
	BRM_SYSTEM_BACKUP_MANAGER__DELETE = 1,
	BRM_SYSTEM_BACKUP_MANAGER__CANCEL_CURRENT_ACTION = 2,
	BRM_SYSTEM_BACKUP__RESTORE = 3,
	//Does not exist in the current model. This action is supposed to be added in the future SDPs.
	BRM_SYSTEM_BACKUP__CONFIRM_RESTORE = 4,
	BRM_SYSTEM_BACKUP__CANCEL_CURRENT_ACTION = 5 ,

	BRM__OperationId_List_End = 6,
	BRM__NO_ACTION = 99,

	BRF_PARTICIPANT__PERMIT_BACKUP = 0,
	BRF_PARTICIPANT__COMMIT_BACKUP = 3,
	BRF_PARTICIPANT__CANCEL_BACKUP = 4,

	BRF_PERSISTENT_DATA_OWNER__PREPARE_BACKUP = 1,

	BRF_PERSISTENT_STORAGE_OWNER__CREATE_BACKUP = 2,
	BRF_PERSISTENT_STORAGE_OWNER__PERMIT_DELETE = 5,
	BRF_PERSISTENT_STORAGE_OWNER__PREPARE_DELETE = 6,
	BRF_PERSISTENT_STORAGE_OWNER__COMMIT_DELETE = 7,
	BRF_PERSISTENT_STORAGE_OWNER__CANCEL_DELETE = 8,
	BRF_PERSISTENT_STORAGE_OWNER__PERMIT_RESTORE = 9,
	BRF_PERSISTENT_STORAGE_OWNER__PREPARE_RESTORE = 10,
	BRF_PERSISTENT_STORAGE_OWNER__COMMIT_RESTORE = 11,
	BRF_PERSISTENT_STORAGE_OWNER__CANCEL_RESTORE = 12,

	BRF_PARTICIPANT_CONTAINER__REPORT_ACTION_PROGRESS = 21,
	BRF_PARTICIPANT_CONTAINER__REPORT_ACTION_RESULT = 22,


} acs_bur_BrfcAdminOperationId;

typedef enum
{
	BRF_SUCCESS = 0,
    BRF_ERROR_DISKSPACE = 1,
    BRF_ERROR_CONFLICT = 2,
    BRF_ERROR_OTHERS = 99


} acs_bur_BrfResultCode;

#endif /* ACS_BUR_BRFCADMINOPERATIONID_H_ */
