#ifndef HEADER_GUARD_FILE__ACS_DSD_MacrosConfig
#define HEADER_GUARD_FILE__ACS_DSD_MacrosConfig ACS_DSD_MacrosConfig.h

/** @file ACS_DSD_MacrosConfig.h
 *	@brief
 *	@author xnicmut (Nicola Muto)
 *	@date 2010-10-04
 *	@version 1.0.0
 *
 *	COPYRIGHT Ericsson AB, 2010
 *	All rights reserved.
 *
 *	The information in this document is the property of Ericsson.
 *	Except as specifically authorized in writing by Ericsson, the receiver of
 *	this document shall keep the information contained herein confidential and
 *	shall protect the same in whole or in part from disclosure and dissemination
 *	to third parties. Disclosure and disseminations to the receivers employees
 *	shall only be made on a strict need to know basis.
 *
 *	REVISION INFO
 *	+========+============+==============+=====================================+
 *	| REV    | DATE       | AUTHOR       | DESCRIPTION                         |
 *	+========+============+==============+=====================================+
 *	| P0.9.1 | 2010-10-04 | xnicmut      | File created.                       |
 *	+========+============+==============+=====================================+
 */

#include <netinet/in.h>

#include "ACS_DSD_MacrosCustomConfig.h"

#ifndef ACS_DSD_CONFIG_NETWORKS_SUPPORTED
#define ACS_DSD_CONFIG_NETWORKS_SUPPORTED	2
#endif

#ifndef ACS_DSD_CONFIG_NETWORK_NAME_SIZE_MAX
#define ACS_DSD_CONFIG_NETWORK_NAME_SIZE_MAX	32
#endif

#ifndef ACS_DSD_CONFIG_HOST_NAME_SIZE_MAX
#define ACS_DSD_CONFIG_HOST_NAME_SIZE_MAX	32
#endif

#ifndef ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_USER
#define ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_USER	90
#endif

#ifndef ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_MIN
#define ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_MIN	IPPORT_USERRESERVED
#endif

#ifndef ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_MAX
#define ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_MAX	51946
#endif

#ifndef ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MIN
#define ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MIN	14100
#endif

#ifndef ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MAX
#define ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MAX	51946
#endif

#ifndef ACS_DSD_CONFIG_UNIX_SOCKETS_ROOT_PATH
#define ACS_DSD_CONFIG_UNIX_SOCKETS_ROOT_PATH	"/var/run/ap/" //This path can end with the slash character '/'
#endif

#ifndef ACS_DSD_CONFIG_DSDAPI_UNIX_SOCKET_SAP_ID
#define ACS_DSD_CONFIG_DSDAPI_UNIX_SOCKET_SAP_ID "dsdapi_protocol_sap"
#endif

#ifndef ACS_DSD_CONFIG_CPAP_INET_SOCKET_SAP_PORT
#define ACS_DSD_CONFIG_CPAP_INET_SOCKET_SAP_PORT 14000
#endif

#ifndef ACS_DSD_CONFIG_CPAP_INET_SOCKET_SAP_ID
#define ACS_DSD_CONFIG_CPAP_INET_SOCKET_SAP_ID "14000"
#endif

#ifndef ACS_DSD_CONFIG_DSDDSD_INET_SOCKET_SAP_ID
#define ACS_DSD_CONFIG_DSDDSD_INET_SOCKET_SAP_ID "14002"
#endif

#ifndef ACS_DSD_CONFIG_SYSTEM_NAME_PREFIX_AP
#define ACS_DSD_CONFIG_SYSTEM_NAME_PREFIX_AP "AP"
#endif

#ifndef ACS_DSD_CONFIG_SYSTEM_NAME_PREFIX_BC
#define ACS_DSD_CONFIG_SYSTEM_NAME_PREFIX_BC "BC"
#endif

#ifndef ACS_DSD_CONFIG_SYSTEM_NAME_PREFIX_CP
#define ACS_DSD_CONFIG_SYSTEM_NAME_PREFIX_CP "CP"
#endif

#ifndef ACS_DSD_CONFIG_FILENAME_SIZE_MAX
#define ACS_DSD_CONFIG_FILENAME_SIZE_MAX	256
#endif

#ifndef ACS_DSD_CONFIG_NODE_NAME_SIZE_MAX
#define ACS_DSD_CONFIG_NODE_NAME_SIZE_MAX	16
#endif

#ifndef ACS_DSD_CONFIG_SYSTEM_NAME_SIZE_MAX
#define ACS_DSD_CONFIG_SYSTEM_NAME_SIZE_MAX	16
#endif

#ifndef ACS_DSD_CONFIG_APP_DOMAIN_NAME_SIZE_MAX
#define ACS_DSD_CONFIG_APP_DOMAIN_NAME_SIZE_MAX	8
#endif

#ifndef ACS_DSD_CONFIG_APP_SERVICE_NAME_SIZE_MAX
#define ACS_DSD_CONFIG_APP_SERVICE_NAME_SIZE_MAX	16
#endif

#ifndef ACS_DSD_CONFIG_PROCESS_NAME_SIZE_MAX
#define ACS_DSD_CONFIG_PROCESS_NAME_SIZE_MAX	32
#endif

#ifndef ACS_DSD_CONFIG_AP_CLUSTERS_SUPPORTED
#define ACS_DSD_CONFIG_AP_CLUSTERS_SUPPORTED	32
#endif

#ifndef ACS_DSD_CONFIG_AP_NODES_PER_CLUSTER_SUPPORTED
#define ACS_DSD_CONFIG_AP_NODES_PER_CLUSTER_SUPPORTED	2
#endif

#ifndef ACS_DSD_CONFIG_CP_NODES_SUPPORTED
#define ACS_DSD_CONFIG_CP_NODES_SUPPORTED	128
#endif

#ifndef ACS_DSD_CONFIG_BC_ID_SET_START
#define ACS_DSD_CONFIG_BC_ID_SET_START 0
#endif

#ifndef ACS_DSD_CONFIG_BC_ID_SET_END
#define ACS_DSD_CONFIG_BC_ID_SET_END 999
#endif

#ifndef ACS_DSD_CONFIG_CP_ID_SET_START
#define ACS_DSD_CONFIG_CP_ID_SET_START 1000
#endif

#ifndef ACS_DSD_CONFIG_CP_ID_SET_END
#define ACS_DSD_CONFIG_CP_ID_SET_END 1999
#endif

#ifndef ACS_DSD_CONFIG_AP_ID_SET_START
#define ACS_DSD_CONFIG_AP_ID_SET_START 2000
#endif

#ifndef ACS_DSD_CONFIG_AP_ID_SET_END
#define ACS_DSD_CONFIG_AP_ID_SET_END 2999
#endif

#ifndef ACS_DSD_CONFIG_IMM_DN_PATH_SIZE_MAX
#define ACS_DSD_CONFIG_IMM_DN_PATH_SIZE_MAX 512
#endif

#ifndef ACS_DSD_CONFIG_IMM_RDN_SIZE_MAX
#define ACS_DSD_CONFIG_IMM_RDN_SIZE_MAX 256
#endif

#ifndef ACS_DSD_CONFIG_IMM_SERVICE_INFO_CLASS_NAME
#define ACS_DSD_CONFIG_IMM_SERVICE_INFO_CLASS_NAME "SRVInfo"
#endif

#ifndef ACS_DSD_CONFIG_IMM_REGISTRATION_TABLE_CLASS_NAME
#define ACS_DSD_CONFIG_IMM_REGISTRATION_TABLE_CLASS_NAME "SRTNode"
#endif

#ifndef ACS_DSD_CONFIG_IMM_DSD_CLASS_NAME
#define ACS_DSD_CONFIG_IMM_DSD_CLASS_NAME "DSD"
#endif

#ifndef ACS_DSD_CONFIG_IMM_STATE_ATTR_NAME
#define ACS_DSD_CONFIG_IMM_STATE_ATTR_NAME "state"
#endif

#ifndef ACS_DSD_CONFIG_IMM_CONN_TYPE_ATTR_NAME
#define ACS_DSD_CONFIG_IMM_CONN_TYPE_ATTR_NAME "conn_type"
#endif

#ifndef ACS_DSD_CONFIG_IMM_INET_ADDRESSES_ATTR_NAME
#define ACS_DSD_CONFIG_IMM_INET_ADDRESSES_ATTR_NAME "inet_addresses"
#endif

#ifndef ACS_DSD_CONFIG_IMM_UNIX_ADDRESSES_ATTR_NAME
#define ACS_DSD_CONFIG_IMM_UNIX_ADDRESSES_ATTR_NAME "unix_addresses"
#endif

#ifndef ACS_DSD_CONFIG_IMM_VISIBILITY_ATTR_NAME
#define ACS_DSD_CONFIG_IMM_VISIBILITY_ATTR_NAME "visibility"
#endif

#ifndef ACS_DSD_CONFIG_IMM_PROCESS_NAME_ATTR_NAME
#define ACS_DSD_CONFIG_IMM_PROCESS_NAME_ATTR_NAME "proc_name"
#endif

#ifndef ACS_DSD_CONFIG_IMM_PID_ATTR_NAME
#define ACS_DSD_CONFIG_IMM_PID_ATTR_NAME "pid"
#endif

#ifndef ACS_DSD_CONFIG_OCP_ACCEPT_CONFIRM_MSG_SIZE
#define ACS_DSD_CONFIG_OCP_ACCEPT_CONFIRM_MSG_SIZE 2
#endif

#ifndef ACS_DSD_CONFIG_INET_PORT_SEARCH_MAX_RETRIES
#define ACS_DSD_CONFIG_INET_PORT_SEARCH_MAX_RETRIES 1000
#endif

#ifndef ACS_DSD_CONFIG_CP_LOADING_FROM_CS
#define ACS_DSD_CONFIG_CP_LOADING_FROM_CS 1
#endif

#ifndef ACS_DSD_CONFIG_AP_LOADING_FROM_CS
#define ACS_DSD_CONFIG_AP_LOADING_FROM_CS 1
#endif

#ifndef ACS_DSD_CONFIG_DISABLE_PEER_CHECK_FOR_SEA_TEST
#define ACS_DSD_CONFIG_DISABLE_PEER_CHECK_FOR_SEA_TEST 0
#endif

#ifndef ACS_DSD_CONFIG_MESSAGE_DUMPING_BUFFER_SIZE
#define ACS_DSD_CONFIG_MESSAGE_DUMPING_BUFFER_SIZE 128
#endif

#ifndef ACS_DSD_CONFIG_MESSAGE_DUMPING_LINE_SIZE
#define ACS_DSD_CONFIG_MESSAGE_DUMPING_LINE_SIZE 16
#endif

#define ACS_DSD_CONFIG_AP_NODES_SUPPORTED	(ACS_DSD_CONFIG_AP_CLUSTERS_SUPPORTED * ACS_DSD_CONFIG_AP_NODES_PER_CLUSTER_SUPPORTED)

#define ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_MAX	108 	// 108 as defined in sys/un.h

#ifndef ACS_DSD_CONFIG_PROC_FS_PATH
#define ACS_DSD_CONFIG_PROC_FS_PATH	"/proc/"
#endif

#ifndef ACS_DSD_CONFIG_PROC_STATUS_FILENAME
#define ACS_DSD_CONFIG_PROC_STATUS_FILENAME	"status"
#endif

#ifndef ACS_DSD_CONFIG_PROC_CMD_LINE_FILENAME
#define ACS_DSD_CONFIG_PROC_CMD_LINE_FILENAME	"cmdline"
#endif

//#define ACS_DSD_WARNING_CUSTOM_MESSAGES_ENABLED
#define ACS_DSD_API_TRACING_ACTIVE
#define ACS_DSD_API_TRACE_FUNCTION_HAS_SOURCE_INFO
//#define ACS_DSD_API_TRACE_FUNCTION_USE_PRETTY_FUNCTION_NAME

namespace acs_dsd {
	/** @brief DSD API configuration constants.
	 *
	 *	ConfigurationConstants enumeration detailed description
	 */
	enum ConfigurationConstants {
		CONFIG_NETWORKS_SUPPORTED									=	ACS_DSD_CONFIG_NETWORKS_SUPPORTED,									///< CONFIG_NETWORKS_SUPPORTED description
		CONFIG_IP4_ADDRESS_STRING_SIZE_MAX				= INET_ADDRSTRLEN,																		///< CONFIG_IP4_ADDRESS_STRING_LENGTH description
		CONFIG_NETWORK_NAME_SIZE_MAX							= ACS_DSD_CONFIG_NETWORK_NAME_SIZE_MAX,								///< CONFIG_NETWORK_NAME_STRING_LENGTH description
		CONFIG_HOST_NAME_SIZE_MAX									= ACS_DSD_CONFIG_HOST_NAME_SIZE_MAX,									///< CONFIG_HOST_NAME_SIZE_MAX description
		CONFIG_UNIX_SOCK_NAME_SIZE_MAX						=	ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_MAX,							///< CONFIG_UNIX_SOCK_NAME_SIZE_MAX description (108 as defined in sys/un.h)

#if ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_USER > (ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_MAX - 18)
		CONFIG_UNIX_SOCK_NAME_SIZE_USER						=	ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_MAX - 18,				///< CONFIG_UNIX_SOCK_NAME_SIZE_USER description
#else
		CONFIG_UNIX_SOCK_NAME_SIZE_USER						=	ACS_DSD_CONFIG_UNIX_SOCK_NAME_SIZE_USER,						///< CONFIG_UNIX_SOCK_NAME_SIZE_USER description
#endif

		CONFIG_INET_IP4_SERVICE_PORT_MIN					=	ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_MIN,						///< CONFIG_INET_IP4_SERVICE_PORT_MIN description
		CONFIG_INET_IP4_SERVICE_PORT_MAX					=	ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_MAX,						///< CONFIG_INET_IP4_SERVICE_PORT_MAX description

		CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MIN	=	ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MIN,	///< CONFIG_INET_IP4_SERVICE_PORT_MIN description
		CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MAX	=	ACS_DSD_CONFIG_INET_IP4_SERVICE_PORT_SELECTOR_MAX,	///< CONFIG_INET_IP4_SERVICE_PORT_MAX description

		CONFIG_FILENAME_SIZE_MAX									=	ACS_DSD_CONFIG_FILENAME_SIZE_MAX,										///< CONFIG_FILENAME_LENGTH_MAX description
		CONFIG_NODE_NAME_SIZE_MAX									=	ACS_DSD_CONFIG_NODE_NAME_SIZE_MAX,									///< CONFIG_NODE_NAME_SIZE_MAX description
		CONFIG_SYSTEM_NAME_SIZE_MAX								=	ACS_DSD_CONFIG_SYSTEM_NAME_SIZE_MAX,								///< CONFIG_SYSTEM_NAME_SIZE_MAX description

		CONFIG_APP_DOMAIN_NAME_SIZE_MAX						=	ACS_DSD_CONFIG_APP_DOMAIN_NAME_SIZE_MAX,						///< CONFIG_APP_DOMAIN_NAME_SIZE_MAX description
		CONFIG_APP_SERVICE_NAME_SIZE_MAX					=	ACS_DSD_CONFIG_APP_SERVICE_NAME_SIZE_MAX,						///< CONFIG_APP_SERVICE_NAME_SIZE_MAX description
		CONFIG_PROCESS_NAME_SIZE_MAX							=	ACS_DSD_CONFIG_PROCESS_NAME_SIZE_MAX,								///< CONFIG_PROCESS_NAME_SIZE_MAX description

		CONFIG_AP_CLUSTERS_SUPPORTED							=	ACS_DSD_CONFIG_AP_CLUSTERS_SUPPORTED,								///< CONFIG_AP_CLUSTERS_SUPPORTED description
		CONFIG_AP_NODES_PER_CLUSTER_SUPPORTED			=	ACS_DSD_CONFIG_AP_NODES_PER_CLUSTER_SUPPORTED,			///< CONFIG_AP_NODES_PER_CLUSTER_SUPPORTED description
		CONFIG_CP_NODES_SUPPORTED									=	ACS_DSD_CONFIG_CP_NODES_SUPPORTED,									///< CONFIG_CP_NODES_SUPPORTED description
		CONFIG_AP_NODES_SUPPORTED									=	ACS_DSD_CONFIG_AP_NODES_SUPPORTED,									///< CONFIG_AP_NODES_SUPPORTED description
		CONFIG_AP_ID_SET_START										=	ACS_DSD_CONFIG_AP_ID_SET_START,											///< CONFIG_AP_ID_SET_START description
		CONFIG_AP_ID_SET_END											=	ACS_DSD_CONFIG_AP_ID_SET_END,												///< CONFIG_AP_ID_SET_END description
		CONFIG_BC_ID_SET_START										=	ACS_DSD_CONFIG_BC_ID_SET_START,											///< CONFIG_BC_ID_SET_START description
		CONFIG_BC_ID_SET_END											=	ACS_DSD_CONFIG_BC_ID_SET_END,												///< CONFIG_BC_ID_SET_END description
		CONFIG_CP_ID_SET_START										=	ACS_DSD_CONFIG_CP_ID_SET_START,											///< CONFIG_CP_ID_SET_START description
		CONFIG_CP_ID_SET_END											=	ACS_DSD_CONFIG_CP_ID_SET_END,												///< CONFIG_CP_ID_SET_END description

		CONFIG_IMM_DN_PATH_SIZE_MAX								=	ACS_DSD_CONFIG_IMM_DN_PATH_SIZE_MAX,								///< CONFIG_IMM_DN_PATH_SIZE_MAX description
		CONFIG_IMM_RDN_SIZE_MAX										=	ACS_DSD_CONFIG_IMM_RDN_SIZE_MAX,										///< CONFIG_IMM_RDN_SIZE_MAX description

		CONFIG_OCP_ACCEPT_CONFIRM_MSG_SIZE				=	ACS_DSD_CONFIG_OCP_ACCEPT_CONFIRM_MSG_SIZE,					///< CONFIG_OCP_ACCEPT_CONFIRM_MSG_SIZE description

		CONFIG_INET_PORT_SEARCH_MAX_RETRIES				=	ACS_DSD_CONFIG_INET_PORT_SEARCH_MAX_RETRIES,				///< CONFIG_INET_PORT_SEARCH_MAX_RETRIES description

		CONFIG_MESSAGE_DUMPING_BUFFER_SIZE				=	ACS_DSD_CONFIG_MESSAGE_DUMPING_BUFFER_SIZE,					///< CONFIG_MESSAGE_DUMPING_BUFFER_SIZE description
		CONFIG_MESSAGE_DUMPING_LINE_SIZE					=	ACS_DSD_CONFIG_MESSAGE_DUMPING_LINE_SIZE,						///< CONFIG_MESSAGE_DUMPING_LINE_SIZE description

		CONFIG_CPAP_INET_SOCKET_SAP_PORT					=	ACS_DSD_CONFIG_CPAP_INET_SOCKET_SAP_PORT						///< CONFIG_CPAP_INET_SOCKET_SAP_PORT description
	};
}

#endif // HEADER_GUARD_FILE__ACS_DSD_MacrosConfig
